project/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.user_register_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("<str:username>/", views.dashboard, name="dashboard"),
]

project/main/urls.py
from django.urls import path

from . import views

app_name = "main"

urlpatterns = [
    path("", views.home, name="home"),
]

project/scores/urls.py
from django.urls import path

from . import views

app_name = "scores"

urlpatterns = [
    path("create/", views.create_score, name="create_score"),
    path("read/<slug:slug>/", views.read_score, name="read_score"),
    path("update/<slug:slug>/", views.update_score, name="update_score"),
    path("delete/<slug:slug>/", views.delete_score, name="delete_score"),
    path("getxml/<slug:slug>/", views.get_xml, name="get_xml"),
    path("download/<slug:slug>/", views.download_score, name="download_score"),
]

project/scoresensei/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("scores/", include("scores.urls")),
]

project/scores/models.py
from autoslug import AutoSlugField
from django.conf import settings
from django.db import models
from django.urls import reverse

# Create your models here.


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    print(instance.user.username)
    return "user_{0}/{1}".format(instance.user.id, filename)


class Score(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    score_title = models.CharField(max_length=100)
    score_slug = AutoSlugField(populate_from="score_title", unique_with="user")
    score_xml = models.FileField(max_length=500, upload_to=user_directory_path)
    score_json = models.FileField(max_length=500, upload_to=user_directory_path)

    def save(self, *args, **kwargs):
        # check if the title already exists
        if Score.objects.filter(user=self.user, score_title=self.score_title).exists():
            suffix = 1
            while True:
                new_title = f"{self.score_title}-{suffix}"
                if not Score.objects.filter(
                    user=self.user, score_title=new_title
                ).exists():
                    self.score_title = new_title
                    break
                suffix += 1

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("read_score", kwargs={"slug": self.score_slug})

project/scores/views.py
import json
import threading
from dataclasses import asdict, dataclass, field
from pathlib import Path
from time import sleep

from django.contrib.auth.decorators import login_required
from django.core.files import File
from django.http import FileResponse, HttpResponse
from django.shortcuts import redirect, render

from .models import Score
from .musicxml_generator import update_sheet
from .utils import get_note_names, template1, template2

# Create your views here.


@dataclass
class Sheet:
    note_start_times: dict = field(default_factory=dict)
    buffer_note_start_times: dict = field(default_factory=dict)
    beat: int = 0
    measure: int = 1
    previous_note: list = field(
        default_factory=list
    )  # [start_time, duration, dotted, voice, start_beat]
    chord: bool = False
    backup: bool = False  # flag for when a <backup> is used
    last_note_start_time: float = 0
    # voice: int = 1
    dynamic: str = "unknown"
    last_dynamic: str = "unknown"
    create_measure: bool = False
    l1_note_buffer: list = field(default_factory=list)
    l2_note_buffer: list = field(default_factory=list)
    last_note_end_time: float = 0  # when the last note ends
    note_names: list = field(default_factory=list)
    bpm: int = 60
    time_sig_beats: int = 4
    pedal_pressed: bool = False
    notes_during_pedal: bool = False
    pedal_markup_buffer: list = field(default_factory=list)
    after_backup_beat: int = 32
    backup_voice: int = 1


note_list = []

condition = threading.Condition()
modified = False


@login_required(redirect_field_name=None)
def create_score(request):
    user_id = request.user
    username = request.user.username
    score_title = request.POST["score-title"].lower()

    xml_path = Path(f"{score_title}.musicxml")
    json_path = Path(f"{score_title}.json")

    # django creates a copy of the file for the db
    with open(xml_path, "w+") as xml_fp, open(json_path, "w+") as json_fp:
        xml_fp.writelines(template1)

        xml_fp.write("<key>\n")
        xml_fp.write(f"<fifths>{request.POST['key']}</fifths>\n")
        xml_fp.write("</key>\n")

        xml_fp.write("<time>\n")
        xml_fp.write(f"<beats>{request.POST['Time Signature']}</beats>\n")
        xml_fp.write("<beat-type>4</beat-type>\n")
        xml_fp.write("</time>\n")

        xml_fp.writelines(template2)

        sheet = Sheet(
            time_sig_beats=int(request.POST["Time Signature"]),
            bpm=int(request.POST["bpm"]),
            note_names=get_note_names(request.POST["key"]),
            previous_note=[None, None, None, None],
        )
        json_fp.write(json.dumps(asdict(sheet)))

        score = Score(
            user=user_id,
            score_title=score_title,
            score_xml=File(xml_fp),
            score_json=File(json_fp),
        )
        score.save()

    # delete original file
    xml_path.unlink()
    json_path.unlink()

    return redirect("accounts:dashboard", username=username)


@login_required(redirect_field_name=None)
def read_score(request, slug):
    score = Score.objects.get(user_id=request.user, score_slug=slug)
    return render(request, "scores/user_page.html", {"score": score})


@login_required(redirect_field_name=None)
def update_score(request, slug):
    event = json.loads(request.body)["event"]
    if event[0] == 144:
        event[3] += 0.05
        sleep(0.05)  # wait for any off_notes
    note_list.append(event)
    
    with condition:

        
        print(f"Post Append: {note_list}")
        event = min(note_list, key=lambda event: event[3])  # return smallest event_time
        note_list.pop(
            note_list.index(event)
        )  # remove smallest event_time from note_list
        print(f"After pop: {note_list}")
        print(f"{event} Entering musicxml generator..")

        score = Score.objects.get(user_id=request.user, score_slug=slug)

        with open(score.score_json.path, "r+") as json_fp:
            sheet = Sheet(**json.loads(json_fp.read()))
            sheet = update_sheet(sheet, score.score_xml.path, event)

            json_fp.seek(0)
            json_fp.write(json.dumps(asdict(sheet)))
            json_fp.truncate()

        global modified

        modified = True
        condition.notify()

    return HttpResponse(status=200)


@login_required(redirect_field_name=None)
def delete_score(request, slug):
    score = Score.objects.get(user_id=request.user, score_slug=slug)
    score.delete()
    return redirect("accounts:dashboard", username=request.user.username)


@login_required(redirect_field_name=None)
def get_xml(request, slug):
    with condition:
        global modified
        while not modified:
            condition.wait()

        score = Score.objects.get(user_id=request.user, score_slug=slug)

        modified = False

    return HttpResponse(open(score.score_xml.path).read(), content_type="text/xml")


@login_required(redirect_field_name=None)
def download_score(request, slug):
    score = Score.objects.get(user_id=request.user, score_slug=slug)
    xml_fp = open(score.score_xml.path, "rb")
    return FileResponse(xml_fp, filename=f"{score.score_slug}.musicxml")

project/scores/templates/scores/user_page.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
  <!-- BUTTONS -->
  <a href="{% url 'accounts:dashboard' username=user.username %}" class="btn mt-4">BACK</a>

  <button id="startBtn" class="btn mt-4">BEGIN RECORDING</button>

  <button id="stopBtn" class="btn mt-4">STOP RECORDING</button>

  <a href="{% url 'scores:download_score' slug=score.score_slug %}" class="btn mt-4">Download Score</a>

  <!-- MAIN CONTENT -->

  <!-- DISPLAY -->
  <div>
    <div class="sheet-music-container">
      <div id="osmdCanvas"></div>
    </div>
  </div>

  <script src="{% static 'main/opensheetmusicdisplay.min.js' %}"></script>
  <script>
    var osmd = new opensheetmusicdisplay.OpenSheetMusicDisplay('osmdCanvas', {
      autoResize: true,
      backend: 'svg',
      drawTitle: false,
      pageFormat: 'A4_P'
    })
    
    osmd.load("{% url 'scores:download_score' slug=score.score_slug %}").then(function () {
      osmd.render()
    })
  </script>

  <!-- SHEET MUSIC SETUP -->
  <script src="https://cdn.jsdelivr.net/npm/webmidi@latest/dist/iife/webmidi.iife.js"></script>
  <script>
    document.getElementById('startBtn').addEventListener('click', function () {
      WebMidi.enable()
        .then(onEnabled)
        .catch((err) => alert(err))
      pollServer()
    })
    
    document.getElementById('stopBtn').addEventListener('click', function () {
      WebMidi.disable()
    })
    
    function pollServer() {
      fetch("{% url 'scores:get_xml' slug=score.score_slug %}")
        .then((response) => response.text())
        .then((xml) => {
          if (xml) {
            osmd.load(xml).then(function () {
              osmd.render()
            })
          }
          pollServer()
        })
        .catch((error) => {
          console.error('Error during long polling: ', error)
        })
    }
    
    function onEnabled() {
      const mySynth = WebMidi.inputs[0]
    
      var csrftoken = '{{ csrf_token }}'
    
      mySynth.channels[1].addListener('noteon', (e) => {
        event = e.message.data
        event.push(new Date().getTime() / 1000)
        fetch("{% url 'scores:update_score' slug=score.score_slug %}", {
          method: 'POST',
          headers: { 'Content-type': 'application/json', 'X-CSRFToken': csrftoken },
          body: JSON.stringify({ event: event })
        })
      })
    
      mySynth.channels[1].addListener('noteoff', (e) => {
        event = e.message.data
        event.push(new Date().getTime() / 1000)
        fetch("{% url 'scores:update_score' slug=score.score_slug %}", {
          method: 'POST',
          headers: { 'Content-type': 'application/json', 'X-CSRFToken': csrftoken },
          body: JSON.stringify({ event: event })
        })
      })
    }
  </script>
{% endblock %}