project/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.user_register_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("<str:username>/", views.dashboard, name="dashboard"),
]

project/main/urls.py
from django.urls import path

from . import views

app_name = "main"

urlpatterns = [
    path("", views.home, name="home"),
]

project/scoresensei/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("scores/", include("scores.urls")),
]

project/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SCORE SENSEI</title>
    <link rel="stylesheet" href="{% static 'main/style.css' %}" />
    <link rel="shortcut icon" type="image/jpg" href="{% static 'main/SSLOGOICON.png' %}" />
  </head>
  <body style="margin: 0;">
    <!-- NAVIGATION BAR -->
    <nav>
      <a href="{% url 'main:home' %}" class="logo"><img src="{% static 'main/SSLOGOv3.png' %}" alt="Score Sensei Logo" height="85" width="425" /></a>
      <!-- Using unordered list for nav bar -->
      <!-- Eventually we will have to fill hrefs with actual file paths to other pages -->
      <ul>
        <li>
          <a href="{% url 'main:home' %}" class="link">About Us</a>
        </li>
        <li>
          <a href="https://github.com/kitchy115/CS-490-Capstone-Project" class="link">GitHub</a>
        </li>

        {% if user.is_authenticated %}
          <li>
            <a href="{% url 'accounts:dashboard' username=user.username %}" class="link">My Scores</a>
          </li>
        {% endif %}

        {% if user.is_authenticated %}
          <li>
            <a href="{% url 'accounts:logout' %}" class="link">Logout</a>
          </li>
        {% else %}
          <li>
            <a href="{% url 'accounts:login' %}" class="link">Login</a>
          </li>
        {% endif %}
      </ul>
    </nav>

    {% comment %}ALERTS{% endcomment %}
    {% if messages %}
      {% for message in messages %}
        <h1>{{ message }}</h1>
      {% endfor %}
    {% endif %}

    {% block content %}

    {% endblock %}
  </body>
</html>

project/templates/homepage.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>SCORE SENSEI</title>
        <link rel="stylesheet" href="{% static 'css/style.css' %}" />
        <link rel="shortcut icon" type="image/jpg" href="{% static 'img/SSLOGOICON.png' %}"/>
      </head>
      <body style = "margin: 0;">
        <!--NAVIGATION BAR-->
        <nav>
          <a href="#" class="logo">
            <img src = "{% static 'img/SSLOGO.png' %}" alt = "Score Sensei Logo" height="50" width=auto>
          </a>
          <!--Using unordered list for nav bar-->
          <!--Eventually we will have to fill hrefs with actual file paths to other pages-->
          <ul>
            <li><a href="index.html" class="link">About Us</a></li>
            <li><a href="#" class="link">Show Case</a></li>
            <li><a href="https://github.com/kitchy115/CS-490-Capstone-Project" class="link">GitHub</a></li>
            <li><a href="login_page.html" class="link">Login</a></li>
          </ul>
        </nav>

        <!--MAIN CONTENT-->

        <!--can add images here-->
        <div style = "background-color: #2C3526; height: 700px;">
          <h1 style = "font-size: 50px; font-family: Sedgwick; color: white; text-align: center; padding-top: 50px;"> ABOUT US </h1>
        <p style="line-height: 2.0; font-size:20px; font-family: Tech; color: white; text-align: center;">Score Sensei offers the automation that AI transcriptions have in order to free up time for musicians. Our AI model allows musicians to have features capable of  transcribing music live, while also continuing to offer an in-app composition editor to allow the musician to fix any mistakes the AI makes. Which will give our users a fully notated piece of sheet music of their work giving countless musicians more time to perfect their craft. 
        </p>

        <!--IMAGES OR VIDEO HERE-->

        <!--BEGIN BUTTON-->
        <div class = "bcenter">
          <a href="login_page.html" class="btn mt-4">ENTER OUR DOJO</a>
        </div>

        </div>

        <!--FOOTER-->
        <footer style="height:auto; background-color:#2C3526;">
          <h1 style = "font-family: Sedgwick; color: white; text-align: center;">Thanks for visisting! </h1>
        </footer>

      </body>
</html>