project/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.user_register_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("<str:username>/", views.dashboard, name="dashboard"),
]

project/main/urls.py
from django.urls import path

from . import views

app_name = "main"

urlpatterns = [
    path("", views.home, name="home"),
]

project/scores/urls.py
from django.urls import path

from . import views

app_name = "scores"

urlpatterns = [
    path("create/", views.create_score, name="create_score"),
    path("read/<slug:slug>/", views.read_score, name="read_score"),
    path("update/<slug:slug>/", views.update_score, name="update_score"),
    path("delete/<slug:slug>/", views.delete_score, name="delete_score"),
    path("getxml/<slug:slug>/", views.get_xml, name="get_xml"),
    path("download/<slug:slug>/", views.download_score, name="download_score"),
]

project/scoresensei/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("scores/", include("scores.urls")),
]

project/accounts/models.py
from django.db import models

# Create your models here.

project/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegistrationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["username"].widget.attrs.update(
            {
                "type": "text",
                "class": "form-style",
                "placeholder": "Username",
            }
        )
        self.fields["password1"].widget.attrs.update(
            {
                "type": "password",
                "class": "form-style",
                "placeholder": "Password",
            }
        )
        self.fields["password2"].widget.attrs.update(
            {
                "type": "password",
                "class": "form-style",
                "placeholder": "Confirm Password",
            }
        )

        """
        self.fields["filename"].widget.attrs.update(
            {
                "type": "filename",
                "class": "form-style",
                "placeholder": "Enter a filename",
            }
        )
        """

    class Meta:
        model = User
        fields = ["username", "password1", "password2"]


"""
class FileCreation(FileCreationForm):

"""

project/accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import redirect, render

from scores.models import Score

from .forms import RegistrationForm

# Create your views here.


def user_register_login(request):
    if not request.user.is_anonymous:
        return redirect("main:home")

    if request.POST.get("submit") == "register":
        form = RegistrationForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password1"]
            user = authenticate(username=username, password=password)

            login(request, user)
            messages.success(request, "Registration successful")
            return redirect("main:home")
    else:
        form = RegistrationForm()

    if request.POST.get("submit") == "login":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("main:home")
        else:
            messages.error(request, "You have entered an invalid username or password")
            return redirect("accounts:login")

    return render(request, "accounts/register_login_page.html", {"form": form})


def user_logout(request):
    logout(request)
    messages.success(request, "You were logged out")
    return redirect("main:home")


@login_required(redirect_field_name=None)
def dashboard(request, username):
    if username != request.user.username:
        raise Http404

    scores = Score.objects.filter(user=request.user)
    return render(request, "accounts/dashboard_page.html", {"scores": scores})

project/accounts/templates/accounts/dashboard_page.html
{% extends 'base.html' %}

{% block content %}
  <!-- DASHBOARD (MUSIC XML FILES PAGE ON FIGMA) -->
  <h1 style="font-size: 50px; font-family: Tech; color: white">{{ user.username }}'s files:</h1>

  <!-- USER ENTRY SECTION -->
  <div>
    <div class="user-section">
        <form action="{% url 'scores:create_score' %}" method="POST">
          {% csrf_token %}
          <div class="form-group mt-2" style="width: 225px;">
            <input type="text" name="score-title" class="form-style" placeholder="Score title" required />

            <div class="form-group mt-2" style="width: 225px;">
              <input type="number" name="bpm" class="form-style" placeholder="Beats per Minute" required/>
            </div>

            <div class="form-group mt-2" style="width: 225px;">
              <input type="number" name="key" class="form-style" placeholder="Key" required/>
            </div>

            <div class = "custom-select" style = "width: 225px;">
              <select name = "Time Signature" id = "Time Signature">
                <option value="0">Time Signature</option>
                <option value="4">4/4</option>
                <option value="3">3/4</option>
                <option value="2">2/4</option>
              </select>
            </div>

            <!--Script for animations and hovers for select-->
            <script>
              var x, i, j, l, ll, selElmnt, a, b, c;
              /*look for any elements with the class "custom-select":*/
              x = document.getElementsByClassName("custom-select");
              l = x.length;
              for (i = 0; i < l; i++) {
                selElmnt = x[i].getElementsByTagName("select")[0];
                ll = selElmnt.length;
                /*for each element, create a new DIV that will act as the selected item:*/
                a = document.createElement("DIV");
                a.setAttribute("class", "select-selected");
                a.innerHTML = selElmnt.options[selElmnt.selectedIndex].innerHTML;
                x[i].appendChild(a);
                /*for each element, create a new DIV that will contain the option list:*/
                b = document.createElement("DIV");
                b.setAttribute("class", "select-items select-hide");
                for (j = 1; j < ll; j++) {
                  /*for each option in the original select element,
                  create a new DIV that will act as an option item:*/
                  c = document.createElement("DIV");
                  c.innerHTML = selElmnt.options[j].innerHTML;
                  c.addEventListener("click", function(e) {
                      /*when an item is clicked, update the original select box,
                      and the selected item:*/
                      var y, i, k, s, h, sl, yl;
                      s = this.parentNode.parentNode.getElementsByTagName("select")[0];
                      sl = s.length;
                      h = this.parentNode.previousSibling;
                      for (i = 0; i < sl; i++) {
                        if (s.options[i].innerHTML == this.innerHTML) {
                          s.selectedIndex = i;
                          h.innerHTML = this.innerHTML;
                          y = this.parentNode.getElementsByClassName("same-as-selected");
                          yl = y.length;
                          for (k = 0; k < yl; k++) {
                            y[k].removeAttribute("class");
                          }
                          this.setAttribute("class", "same-as-selected");
                          break;
                        }
                      }
                      h.click();
                  });
                  b.appendChild(c);
                }
                x[i].appendChild(b);
                a.addEventListener("click", function(e) {
                    /*when the select box is clicked, close any other select boxes,
                    and open/close the current select box:*/
                    e.stopPropagation();
                    closeAllSelect(this);
                    this.nextSibling.classList.toggle("select-hide");
                    this.classList.toggle("select-arrow-active");
                  });
              }
              function closeAllSelect(elmnt) {
                /*a function that will close all select boxes in the document,
                except the current select box:*/
                var x, y, i, xl, yl, arrNo = [];
                x = document.getElementsByClassName("select-items");
                y = document.getElementsByClassName("select-selected");
                xl = x.length;
                yl = y.length;
                for (i = 0; i < yl; i++) {
                  if (elmnt == y[i]) {
                    arrNo.push(i)
                  } else {
                    y[i].classList.remove("select-arrow-active");
                  }
                }
                for (i = 0; i < xl; i++) {
                  if (arrNo.indexOf(i)) {
                    x[i].classList.add("select-hide");
                  }
                }
              }
              /*if the user clicks anywhere outside the select box,
              then close all select boxes:*/
              document.addEventListener("click", closeAllSelect);
              </script>

          <!--
            <div class = "dropdown">
              <button class = "dropbtn"> Time Signature </button>
              <div class = "drowpdown-content">
                <option value="4">4/4</option>
                <option value="3">3/4</option>
                <option value="2">2/4</option>
              </div>
            </div>
            -->
            <!--
            <div class="cust-select" style="width: 225px">
              <label for="Time Signature" style="color: white; font-size: 24px; font-family: Tech;">Time Signature:</label>
              <select name="Time Signature" id="Time Signature">
                <option value="4">4/4</option>
                <option value="3">3/4</option>
                <option value="2">2/4</option>
              </select>
            </div>
            -->
            <button type="submit" class="btn mt-4" name="submit">Create Score</button>
          </div>
        </form>
    </div>
  </div>

  <!-- HAVE EXISTING FILES DISPLAY HERE -->

  {% for score in scores %}
  <div class = "user-section">
    <h1>{{ score.score_title }}</h1>
    <a href="{% url 'scores:read_score' slug=score.score_slug %}" class="btn mt-4">Open</a>
    <a href="{% url 'scores:delete_score' slug=score.score_slug %}" class="btn mt-4">Delete</a>
    </div>
  {% endfor %}
{% endblock %}

project/accounts/templates/accounts/register_login_page.html
{% extends 'base.html' %}

{% block content %}
  {% comment %}FORM ALERTS{% endcomment %}
  {% if form.errors %}
    {% for field in form %}
      {% for error in field.errors %}
        <h1>{{ error }}</h1>
      {% endfor %}
    {% endfor %}
  {% endif %}

  <!-- MAIN CONTENT -->

  <div class="section">
    <div class="container">
      <div class="row full-height justify-content-center">
        <div class="col-12 text-center align-self-center py-5">
          <div class="section pb-5 pt-5 pt-sm-2 text-center">
            <!-- re add center here -->
            <input class="checkbox" type="checkbox" id="reg-log" name="reg-log" />
            <label for="reg-log"></label>
            <div class="card-3d-wrap mx-auto">
              <div class="card-3d-wrapper">
                <div class="card-front">
                  <div class="center-wrap">
                    <div class="section text-center">
                      <!-- LOGIN FORM -->
                      <form method="POST">
                        {% csrf_token %}
                        <div class="form-group mt-2" style="width: 275px;">
                          <h4 class="mb-4 pb-3">Log In</h4>
                          <input type="text" class="form-style" name="username" placeholder="Username" required />
                          <input type="password" class="form-style" name="password" placeholder="Password" required />
                          <button type="submit" class="btn mt-4" name="submit" value="login">Submit</button>
                        </div>
                      </form>
                      <!-- <p class="mb-0 mt-4 text-center"><a href="login_page.html" class="link">Forgot your password?</a></p> -->
                    </div>
                  </div>
                </div>
                <div class="card-back">
                  <div class="center-wrap">
                    <div class="section text-center">
                      <!-- REGISTER FORM -->
                      <form method="POST">
                        {% csrf_token %}
                        <div class="form-group mt-2" style="width: 275px;">
                          <h4 class="mb-4 pb-3">Sign Up</h4>
                          {{ form.username }}
                          {{ form.password1 }}
                          {{ form.password2 }}
                          <button type="submit" class="btn mt-4" name="submit" value="register">Register</button>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script>
    // Prevents form resubmission when page is refreshed
    if (window.history.replaceState) {
      window.history.replaceState(null, null, window.location.href)
    }
    
    // Function to save checkbox states to Local Storage
    function saveCheckboxStates() {
      const checkboxes = document.querySelectorAll('input[type="checkbox"]')
      checkboxes.forEach((checkbox) => {
        localStorage.setItem(checkbox.id, checkbox.checked)
      })
    }
    
    // Function to load checkbox states from Local Storage
    function loadCheckboxStates() {
      const checkboxes = document.querySelectorAll('input[type="checkbox"]')
      checkboxes.forEach((checkbox) => {
        const savedState = localStorage.getItem(checkbox.id)
        if (savedState !== null) {
          checkbox.checked = savedState === 'true'
        }
      })
    }
    
    // Attach event listener to the checkboxes to save their states
    const checkboxes = document.querySelectorAll('input[type="checkbox"]')
    checkboxes.forEach((checkbox) => {
      checkbox.addEventListener('change', saveCheckboxStates)
    })
    
    // Load checkbox states on page load
    document.addEventListener('DOMContentLoaded', loadCheckboxStates)
  </script>
{% endblock %}